version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./.dev_env/.postgres

  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.dev_env/.postgres
    volumes:
      - ./project:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
