# Generated by Django 3.1.5 on 2021-01-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltv', models.IntegerField()),
                ('ttv', models.IntegerField()),
                ('utm', models.IntegerField()),
                ('day_open_mid', models.FloatField()),
                ('day_net_chg_mid', models.FloatField()),
                ('day_perc_chg_mid', models.FloatField()),
                ('day_high', models.FloatField()),
                ('day_low', models.FloatField()),
                ('ofr_open', models.FloatField()),
                ('ofr_high', models.FloatField()),
                ('ofr_low', models.FloatField()),
                ('ofr_close', models.FloatField()),
                ('bid_open', models.FloatField()),
                ('bid_high', models.FloatField()),
                ('bid_low', models.FloatField()),
                ('bid_close', models.FloatField()),
                ('ltp_open', models.FloatField()),
                ('ltp_high', models.FloatField()),
                ('ltp_low', models.FloatField()),
                ('ltp_close', models.FloatField()),
                ('cons_end', models.BooleanField()),
                ('cons_tick_count', models.IntegerField()),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igstream.epic')),
            ],
        ),
    ]
